name: 'Scott Watkins : Portfolio'
favicon: null
layout_spectrum: 0.8594157812185585
typography_spectrum: 0.27113771717995405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f7'
    - '#3c3c3c'
    - '#c4c4c4'
    - '#848484'
    - '#9ab462'
  brandStrength: 0.7720593248959631
  lightness: 0.5
  saturation: 0.5527993110008538
  rhythmicContrast: 0.5
purpose: []
