name: 'Scott Watkins : Portfolio'
favicon: null
layout_spectrum: 0.8594157812185585
typography_spectrum: 0.27113771717995405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7720593248959631
  lightness: 0.11717205005697906
  saturation: 0.5527993110008538
  rhythmicContrast: 0.9334796881303191
purpose: []
